### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by hermann1514** [D3M80L/hassio-mipow#6]
Hi,
after Upgrade to the latest Build from this AddOn, i can't switch my lights.
Here is the Error:

`
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 575, in _setup_socket
    raise err
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 548, in _setup_socket
    self._sock.connect(filename)
FileNotFoundError: [Errno 2] No such file or directory
2022-08-04 15:23:24 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2684325144] [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 562, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/mipow/light.py", line 258, in async_turn_off
    await self._connect()
  File "/config/custom_components/mipow/light.py", line 337, in _connect
    await self._light.connect()
  File "/config/custom_components/mipow/mipow.py", line 41, in connect
    await self._device.connect(timeout = 9)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 112, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 220, in find_device_by_address
    return await cls.find_device_by_filter(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 249, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 95, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 88, in start
    self._bus = await MessageBus(bus_type=BusType.SYSTEM).connect()
  File "/usr/local/lib/python3.10/site-packages/dbus_next/aio/message_bus.py", line 122, in __init__
    super().__init__(bus_address, bus_type, ProxyObject)
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 85, in __init__
    self._setup_socket()
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 575, in _setup_socket
    raise err
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 548, in _setup_socket
    self._sock.connect(filename)
FileNotFoundError: [Errno 2] No such file or directory
`

Any Idea?
Regards
Hermann

**Comment by D3M80L** [comment]
Hey @hermann1514, sad to hear that it stopped working on your installation.
Could you send me details of your setup? Like OS version, or is it a custom installation?
Few items that may help with your setup
* https://www.home-assistant.io/integrations/bluetooth#d-bus-and-bluez-are-required-on-linux
* and the other issue on this integration that was solved here https://github.com/D3M80L/hassio-mipow/issues/5#issuecomment-1200379442

**Comment by hermann1514** [comment]
Hi,
sorry for my late answer.

I use a docker based installation on a Pi4.

I have added the DBUS Path to the docker File.

Bluez is installed on the hostsystem.

Here are the logfile:


`2022-08-31 13:51:46.074 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2967838456] [org.bluez.Error.Failed] Software caused connection abort
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
await light.async_turn_on(**filter_turn_on_params(light, params))
File "/config/custom_components/mipow/light.py", line 245, in async_turn_on
await self._set_light(rgbw_color, effectId, transition, set_effect=effectSet)
File "/config/custom_components/mipow/light.py", line 378, in _set_light
await self._connect()
File "/config/custom_components/mipow/light.py", line 337, in _connect
await self._light.connect()
File "/config/custom_components/mipow/mipow.py", line 41, in connect
await self._device.connect(timeout = 9)
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 167, in connect
assert_reply(reply)
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Software caused connection abort
2022-08-31 13:51:53.663 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2967838456]
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
await light.async_turn_on(**filter_turn_on_params(light, params))
File "/config/custom_components/mipow/light.py", line 245, in async_turn_on
await self._set_light(rgbw_color, effectId, transition, set_effect=effectSet)
File "/config/custom_components/mipow/light.py", line 378, in _set_light
await self._connect()
File "/config/custom_components/mipow/light.py", line 337, in _connect
await self._light.connect()
File "/config/custom_components/mipow/mipow.py", line 35, in connect
await self._device.disconnect()
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 317, in disconnect
assert self._bus is None
AssertionError
2022-08-31 13:51:53.684 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2967838456] [org.bluez.Error.Failed] Software caused connection abort
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 562, in async_handle_light_off_service
await light.async_turn_off(**filter_turn_off_params(light, params))
File "/config/custom_components/mipow/light.py", line 258, in async_turn_off
await self._connect()
File "/config/custom_components/mipow/light.py", line 337, in _connect
await self._light.connect()
File "/config/custom_components/mipow/mipow.py", line 41, in connect
await self._device.connect(timeout = 9)
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 167, in connect
assert_reply(reply)
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Software caused connection abort`

Do you have any idea?

I use now the latest Homeassistant Version.


Regards
Hermann

**Comment by hermann1514** [comment]
I have another installation with a virtual VM Image (Supervisored).
Here i have the following Error:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mipow/mipow.py:41
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:44:01 (2 occurrences)
Last logged: 14:44:05

[139841477646832] [org.bluez.Error.InProgress] Operation already in progress
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/mipow/light.py", line 245, in async_turn_on
    await self._set_light(rgbw_color, effectId, transition, set_effect=effectSet)
  File "/config/custom_components/mipow/light.py", line 378, in _set_light
    await self._connect()
  File "/config/custom_components/mipow/light.py", line 337, in _connect
    await self._light.connect()
  File "/config/custom_components/mipow/mipow.py", line 41, in connect
    await self._device.connect(timeout = 9)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 107, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 221, in find_device_by_address
    return await cls.find_device_by_filter(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 250, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 96, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 137, in start
    self._stop = await manager.active_scan(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 405, in active_scan
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress

```

Regards
Hermann

**Comment by D3M80L** [comment]
@hermann1514 the last log you attached is more familiar for me.
I had the same problem after update to 2022.07. As HA integrates with BT it takes also an exclusive access to BT, causing that some integrations fail to start.

On my instance, as I'm not using other BT integrations, the solution was to disable the BT integration in home assistant. Go to Settings -> Devices & Servoces-> Integrations. You should see a Bluetooth integration. Click the options on the Bluetooth tile and disable the integration.

Here is the link to documentation: https://www.home-assistant.io/integrations/bluetooth#configuration

I have a plan to update the mipow integration to the new HA way, but that will probably happen later this year.

**Comment by hermann1514** [comment]
Thanks for the Info.
I have diabled BT on Homeassistant. But the Problem was not solved:
Here is the Error:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.core
Source: custom_components/mipow/mipow.py:41
Integration: mipow (documentation)
First occurred: 31. August 2022 um 15:07:57 (16 occurrences)
Last logged: 09:28:42

Error executing service: <ServiceCall light.turn_on (c:01GBWJ3YM80QJY93EAD08NA02V): entity_id=['light.playbulb6_2'], params=>
Error executing service: <ServiceCall light.turn_on (c:01GBWM55QF1SM1EZG3APRA99V2): entity_id=['light.playbulb6_2'], params=>
Error executing service: <ServiceCall light.turn_on (c:01GBWMVN7PQA8FZY83XH9GDCA1): entity_id=['light.playbulb6_2'], params=>
Error executing service: <ServiceCall light.turn_on (c:01GBWN6KB0P4MFRYCPCY4JRSGS): entity_id=['light.playbulb6_2'], params=>
Error executing service: <ServiceCall light.turn_on (c:01GBYHKWCFYCM2S0XF25XGX19P): entity_id=['light.playbulb6_2'], params=>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1731, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/mipow/light.py", line 245, in async_turn_on
    await self._set_light(rgbw_color, effectId, transition, set_effect=effectSet)
  File "/config/custom_components/mipow/light.py", line 378, in _set_light
    await self._connect()
  File "/config/custom_components/mipow/light.py", line 337, in _connect
    await self._light.connect()
  File "/config/custom_components/mipow/mipow.py", line 41, in connect
    await self._device.connect(timeout = 9)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 115, in connect
    raise BleakError(
bleak.exc.BleakError: Device with address 98:4F:4B:11:AC:E6 was not found.
```

it's nice to hear that you want to update the module

Regards
Hermann

**Comment by hermann1514** [comment]
Hi,
I tried a little more with the Bluetooth problem. In the container and in the host, if I want to connect to the playbulb with bluetoothctl, that's no problem. The connection is established. But it's funny that your module doesn't find the lamp. Device with MAC Address <> not found...

Do you have another idea?

**Comment by hermann1514** [comment]
I tested a little more.
In the Docker installation from HA I activated Bluetooth. After that I connected to the playbulb in the docker session via bluetoothctl. After that I was able to switch the Playbulb over your module. As soon as I disconnect with bluetoothctl it stops working.

Now I took an old INTEL NUC with a built-in Bluetooth module and installed HA directly (without virtualization and docker). Then install your module and enter the Bluetooth Playbulbs.
Everything works fine there. All playblubs can be switched perfectly.

Maybe it will help to expand the module or to eliminate some errors - if there are any ;-)

**Comment by D3M80L** [comment]
Thank you @hermann1514 for your deep investigation.
Definetely have to look at the integration soon, as after HA upgrade I've got the same error 'No device found for address'.
As soon as I reach my installation, I will have a look on what is going on there.

**Comment by D3M80L** [comment]
Closing this issue, as the plan is to fix that and support BT stack in Home Assistant #7
